# Generated by Django 5.2.8 on 2025-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
