services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mds_apoia
      POSTGRES_USER: apoia_usuario
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=apoia.settings
      - POSTGRES_DB=mds_apoia
      - POSTGRES_USER=apoia_usuario
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=db
volumes:
  postgres_data:
