# Generated by Django 5.2.8 on 2025-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_vagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
