[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
# Filtro para ignorar avisos internos de bibliotecas
filterwarnings =
    ignore:Converter 'drf_format_suffix' is already registered