name: Django CI

on:
  push:
    branches: [ "main", "develop", "fix/compatibilidade-docker-tests" ]
  pull_request:
    branches: [ "main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Define a pasta padrão para todos os comandos
    defaults:
      run:
        working-directory: ./Apoia+

    steps:
    - uses: actions/checkout@v4

    # Passo 1: Subir o ambiente Docker
    - name: Build and Start Containers
      run: |
        docker-compose up -d --build
        # Espera um pouco para o Banco de Dados acordar (segurança)
        sleep 10

    # Passo 2: Rodar Migrações (Para criar as tabelas no banco de teste)
    - name: Run Migrations
      run: docker-compose exec -T web python manage.py migrate

    # Passo 3: Rodar os Testes
    # O flag -T é importante no CI para não pedir terminal interativo
    - name: Run Tests
      run: docker-compose exec -T web pytest